name: bansara-sia-tracking
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=3.0.2
  - numpy=2.4.4
  - scipy=1.17.1
  - geopandas=1.1.4
  - shapely=2.1.2
  - pyproj=3.7.2
  - fiona=1.10.1
  - esda=2.10.0
  - libpysal=4.15.0
  - mapclassify=2.10.0
  - pyarrow=25.0.0
  - matplotlib=3.10.8
  - pip
